environment:
  ADMIN_TOKEN: $argon2id$v=19$m=65540,t=3,p=<A_STRING_GOES_IN_HERE>
  DATABASE_URL: postgresql://<username>:<password>@<hostname>:<port>/<database>
  RO_DATABASE_URL: postgresql://<ro_username>:<ro_password>@<hostname>:<port>/<database>
  PUSH_INSTALLATION_ID: <ID>
  PUSH_INSTALLATION_KEY: <KEY>

sync:
  ldap:
    username: uid=<username>,ou=users,dc=ldap,dc=example,dc=org
    password: <password>
  target:
    org_id: <from_vaultwarden_organisation>
    app_id: <from_vaultwarden_organisation>