apiVersion: skaffold/v3
kind: Config
deploy:
  helm:
    releases:
      - name: vaultwarden
        chartPath: ./helm-charts/vaultwarden
        namespace: vaultwarden
        createNamespace: true
        useHelmSecrets: true
        valuesFiles:
          - deployment-values.yaml
          - secret-values.yaml