{{- if or .Values.metrics.enable .Values.metrics.metrics }}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: database
stringData:
  url: "{{ default .Values.environment.DATABASE_URL .Values.environment.RO_DATABASE_URL }}"
{{- end }}