{{- if .Values.sync.enable }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "sync.fullname" . }}
  labels:
    {{- include "sync.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "sync.selectorLabels" . | nindent 6 }}
  template:
    metadata:
    {{- with (default .Values.podAnnotations .Values.sync.podAnnotations) }}
      annotations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      labels:
        {{- include "sync.selectorLabels" . | nindent 8 }}
    spec:
      {{- with (default .Values.imagePullSecrets .Values.sync.imagePullSecrets) }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml (default .Values.podSecurityContext .Values.sync.podSecurityContext) | nindent 8 }}
      containers:
        - name: {{ include "sync.name" . }}
          securityContext:
            {{- toYaml .Values.sync.securityContext | nindent 12 }}
          image: "{{ .Values.sync.image.registry }}/{{ .Values.sync.image.repository }}:{{ .Values.sync.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            - /usr/bin/setup-sync.sh
          {{- if .Values.sync.ready }}
          livenessProbe:
            initialDelaySeconds: 0
            periodSeconds: {{ .Values.backup.store.frequency_in_seconds }}
            timeoutSeconds: {{ .Values.backup.store.timeout_in_seconds }}
            exec:
              command:
                - /usr/bin/run-sync.sh
          {{- end }}
          volumeMounts:
            - mountPath: /etc/bitwarden-sync/
              name: {{ include "vaultwarden.fullname" . }}
              readOnly: true
          resources:
            {{- toYaml .Values.sync.resources | nindent 12 }}
      {{- with (default .Values.nodeSelector .Values.sync.nodeSelector) }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with (default .Values.affinity .Values.sync.affinity) }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with (default .Values.tolerations .Values.sync.tolerations) }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        - name: {{ include "vaultwarden.fullname" . }}
          secret:
            secretName: {{ include "vaultwarden.fullname" . }}
            items:
              - key: auth.env
                path: auth.env
{{- end }}