{{- if and .Values.vaultwarden.pv.storageClassName (ne .Values.vaultwarden.pv.storageClassName "manual") }}
---
# Dynamic PVC, fulfilled by the StorageClass (e.g. efs)
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "vaultwarden.name" . }}
spec:
  accessModes:
    - {{ .Values.vaultwarden.pv.accessMode }}
  resources:
    requests:
      storage: {{ .Values.vaultwarden.pv.size }}
  storageClassName: {{ .Values.vaultwarden.pv.storageClassName }}
{{- else }}
---
# Static PVC and PV, usually using static NFS mounts
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "vaultwarden.name" . }}
spec:
  resources:
    requests:
      storage: {{ .Values.vaultwarden.pv.size }}
  accessModes:
    - {{ .Values.vaultwarden.pv.accessMode }}
  storageClassName: manual
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ include "vaultwarden.name" . }}
spec:
  capacity:
    storage: {{ .Values.vaultwarden.pv.size }}
  {{- with (default .Values.pv.mountOptions .Values.vaultwarden.pv.mountOptions) }}
  mountOptions:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  volumeMode: Filesystem
  accessModes:
    - {{ .Values.vaultwarden.pv.accessMode }}
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  claimRef:
    kind: PersistentVolumeClaim
    name: {{ include "vaultwarden.name" . }}
    namespace: {{ .Release.Namespace }}
  nfs:
    path: {{ .Values.vaultwarden.pv.path }}
    server: {{ .Values.pv.server }}
{{- end }}
